"""Upgrade Post2

Revision ID: 186d555943b7
Revises: 9a7e357c8fb5
Create Date: 2023-07-28 17:35:40.787602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186d555943b7'
down_revision = '9a7e357c8fb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer, primary_key=True, index=True),
        sa.Column("title", sa.String, index=True),
        sa.Column("content", sa.String),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("user.id", name="fk_post_user_id")),  # Замените "user" на имя таблицы пользователей, если используется другое имя
        sa.Column('email', sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
