"""Initial

Revision ID: 3726a7f53d69
Revises: 8fa77e16ffac
Create Date: 2023-07-24 21:18:48.244447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3726a7f53d69'
down_revision = '8fa77e16ffac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer, primary_key=True, index=True),
        sa.Column("title", sa.String, index=True),
        sa.Column("content", sa.String),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("user.id", name="fk_post_user_id")),  # Замените "user" на имя таблицы пользователей, если используется другое имя
        sa.Column('email', sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
