"""try2

Revision ID: 4458a9b0d7aa
Revises: dc4967087328
Create Date: 2023-07-28 16:07:22.429387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4458a9b0d7aa'
down_revision = 'dc4967087328'
branch_labels = None
depends_on = None

def upgrade():
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer, primary_key=True, index=True),
        sa.Column("title", sa.String, index=True),
        sa.Column("content", sa.String),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("user.id", name="fk_post_user_id")),  # Замените "user" на имя таблицы пользователей, если используется другое имя
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
