"""add foreign key

Revision ID: 7fbf9ccb1e98
Revises: 186d555943b7
Create Date: 2023-07-28 17:45:50.152863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbf9ccb1e98'
down_revision = '186d555943b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Удаляем старую таблицу "posts"
    op.drop_table('posts')

    # Создаем новую таблицу "posts" с добавлением внешнего ключа "user_id" и ссылкой на "users.id"
    op.create_table('posts',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('user_id', sa.INTEGER(), sa.ForeignKey('user.id'), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='posts_pkey')
    )

    # Создаем индекс на поле "title"
    op.create_index('ix_posts_title', 'posts', ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_post_user_id'),
    sa.PrimaryKeyConstraint('id', name='posts_pkey')
    )
    op.create_index('ix_posts_title', 'posts', ['title'], unique=False)
    op.create_index('ix_posts_id', 'posts', ['id'], unique=False)
    # ### end Alembic commands ###
